#!/bin/bash

# Kernel linear
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "linear" --penalty 1.0 --tfidf 'none' --name "AP PAN17 sklearn SVM linear char 1-1grams P1.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "linear" --penalty 1.0 --tfidf 'none' --name "AP PAN17 sklearn SVM linear char 1-2grams P1.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "linear" --penalty 1.0 --tfidf 'none' --name "AP PAN17 sklearn SVM linear char 1-3grams P1.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "linear" --penalty 1.0 --tfidf 'none' --name "AP PAN17 sklearn SVM linear char 1-4grams P1.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "linear" --penalty 1.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM linear char 1-1grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "linear" --penalty 1.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM linear char 1-2grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "linear" --penalty 1.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM linear char 1-3grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "linear" --penalty 1.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM linear char 1-4grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "linear" --penalty 2.0 --tfidf 'none' --name "AP PAN17 sklearn SVM linear char 1-1grams P2.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "linear" --penalty 2.0 --tfidf 'none' --name "AP PAN17 sklearn SVM linear char 1-2grams P2.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "linear" --penalty 2.0 --tfidf 'none' --name "AP PAN17 sklearn SVM linear char 1-3grams P2.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "linear" --penalty 2.0 --tfidf 'none' --name "AP PAN17 sklearn SVM linear char 1-4grams P2.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "linear" --penalty 2.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM linear char 1-1grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "linear" --penalty 2.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM linear char 1-2grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "linear" --penalty 2.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM linear char 1-3grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "linear" --penalty 2.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM linear char 1-4grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "linear" --penalty 3.0 --tfidf 'none' --name "AP PAN17 sklearn SVM linear char 1-1grams P3.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "linear" --penalty 3.0 --tfidf 'none' --name "AP PAN17 sklearn SVM linear char 1-2grams P3.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "linear" --penalty 3.0 --tfidf 'none' --name "AP PAN17 sklearn SVM linear char 1-3grams P3.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "linear" --penalty 3.0 --tfidf 'none' --name "AP PAN17 sklearn SVM linear char 1-4grams P3.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "linear" --penalty 3.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM linear char 1-1grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "linear" --penalty 3.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM linear char 1-2grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "linear" --penalty 3.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM linear char 1-3grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "linear" --penalty 3.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM linear char 1-4grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4

# Kernel poly
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "poly" --penalty 1.0 --tfidf 'none' --name "AP PAN17 sklearn SVM poly D3 char 1-1grams P1.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "poly" --penalty 1.0 --tfidf 'none' --name "AP PAN17 sklearn SVM poly D3 char 1-2grams P1.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "poly" --penalty 1.0 --tfidf 'none' --name "AP PAN17 sklearn SVM poly D3 char 1-3grams P1.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "poly" --penalty 1.0 --tfidf 'none' --name "AP PAN17 sklearn SVM poly D3 char 1-4grams P1.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "poly" --penalty 1.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM poly D3 char 1-1grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "poly" --penalty 1.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM poly D3 char 1-2grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "poly" --penalty 1.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM poly D3 char 1-3grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "poly" --penalty 1.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM poly D3 char 1-4grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "poly" --penalty 2.0 --tfidf 'none' --name "AP PAN17 sklearn SVM poly D3 char 1-1grams P2.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "poly" --penalty 2.0 --tfidf 'none' --name "AP PAN17 sklearn SVM poly D3 char 1-2grams P2.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "poly" --penalty 2.0 --tfidf 'none' --name "AP PAN17 sklearn SVM poly D3 char 1-3grams P2.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "poly" --penalty 2.0 --tfidf 'none' --name "AP PAN17 sklearn SVM poly D3 char 1-4grams P2.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "poly" --penalty 2.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM poly D3 char 1-1grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "poly" --penalty 2.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM poly D3 char 1-2grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "poly" --penalty 2.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM poly D3 char 1-3grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "poly" --penalty 2.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM poly D3 char 1-4grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "poly" --penalty 3.0 --tfidf 'none' --name "AP PAN17 sklearn SVM poly D3 char 1-1grams P3.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "poly" --penalty 3.0 --tfidf 'none' --name "AP PAN17 sklearn SVM poly D3 char 1-2grams P3.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "poly" --penalty 3.0 --tfidf 'none' --name "AP PAN17 sklearn SVM poly D3 char 1-3grams P3.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "poly" --penalty 3.0 --tfidf 'none' --name "AP PAN17 sklearn SVM poly D3 char 1-4grams P3.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "poly" --penalty 3.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM poly D3 char 1-1grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "poly" --penalty 3.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM poly D3 char 1-2grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "poly" --penalty 3.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM poly D3 char 1-3grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "poly" --penalty 3.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM poly D3 char 1-4grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4


python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "poly" --penalty 1.0 --tfidf 'none' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-1grams P1.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "poly" --penalty 1.0 --tfidf 'none' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-2grams P1.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "poly" --penalty 1.0 --tfidf 'none' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-3grams P1.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "poly" --penalty 1.0 --tfidf 'none' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-4grams P1.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "poly" --penalty 1.0 --tfidf 'tfidf' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-1grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "poly" --penalty 1.0 --tfidf 'tfidf' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-2grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "poly" --penalty 1.0 --tfidf 'tfidf' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-3grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "poly" --penalty 1.0 --tfidf 'tfidf' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-4grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "poly" --penalty 2.0 --tfidf 'none' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-1grams P2.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "poly" --penalty 2.0 --tfidf 'none' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-2grams P2.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "poly" --penalty 2.0 --tfidf 'none' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-3grams P2.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "poly" --penalty 2.0 --tfidf 'none' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-4grams P2.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "poly" --penalty 2.0 --tfidf 'tfidf' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-1grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "poly" --penalty 2.0 --tfidf 'tfidf' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-2grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "poly" --penalty 2.0 --tfidf 'tfidf' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-3grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "poly" --penalty 2.0 --tfidf 'tfidf' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-4grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "poly" --penalty 3.0 --tfidf 'none' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-1grams P3.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "poly" --penalty 3.0 --tfidf 'none' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-2grams P3.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "poly" --penalty 3.0 --tfidf 'none' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-3grams P3.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "poly" --penalty 3.0 --tfidf 'none' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-4grams P3.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "poly" --penalty 3.0 --tfidf 'tfidf' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-1grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "poly" --penalty 3.0 --tfidf 'tfidf' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-2grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "poly" --penalty 3.0 --tfidf 'tfidf' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-3grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "poly" --penalty 3.0 --tfidf 'tfidf' --degree 2 --name "AP PAN17 sklearn SVM poly D2 char 1-4grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4


python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "poly" --penalty 1.0 --tfidf 'none' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-1grams P1.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "poly" --penalty 1.0 --tfidf 'none' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-2grams P1.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "poly" --penalty 1.0 --tfidf 'none' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-3grams P1.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "poly" --penalty 1.0 --tfidf 'none' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-4grams P1.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "poly" --penalty 1.0 --tfidf 'tfidf' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-1grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "poly" --penalty 1.0 --tfidf 'tfidf' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-2grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "poly" --penalty 1.0 --tfidf 'tfidf' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-3grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "poly" --penalty 1.0 --tfidf 'tfidf' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-4grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "poly" --penalty 2.0 --tfidf 'none' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-1grams P2.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "poly" --penalty 2.0 --tfidf 'none' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-2grams P2.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "poly" --penalty 2.0 --tfidf 'none' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-3grams P2.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "poly" --penalty 2.0 --tfidf 'none' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-4grams P2.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "poly" --penalty 2.0 --tfidf 'tfidf' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-1grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "poly" --penalty 2.0 --tfidf 'tfidf' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-2grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "poly" --penalty 2.0 --tfidf 'tfidf' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-3grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "poly" --penalty 2.0 --tfidf 'tfidf' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-4grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "poly" --penalty 3.0 --tfidf 'none' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-1grams P3.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "poly" --penalty 3.0 --tfidf 'none' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-2grams P3.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "poly" --penalty 3.0 --tfidf 'none' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-3grams P3.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "poly" --penalty 3.0 --tfidf 'none' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-4grams P3.0" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "poly" --penalty 3.0 --tfidf 'tfidf' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-1grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "poly" --penalty 3.0 --tfidf 'tfidf' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-2grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "poly" --penalty 3.0 --tfidf 'tfidf' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-3grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "poly" --penalty 3.0 --tfidf 'tfidf' --degree 4 --name "AP PAN17 sklearn SVM poly D4 char 1-4grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn Linear SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4


# Kernel RBF
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "rbf" --penalty 1.0 --tfidf 'none' --name "AP PAN17 sklearn SVM rbf char 1-1grams P1.0" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "rbf" --penalty 1.0 --tfidf 'none' --name "AP PAN17 sklearn SVM rbf char 1-2grams P1.0" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "rbf" --penalty 1.0 --tfidf 'none' --name "AP PAN17 sklearn SVM rbf char 1-3grams P1.0" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "rbf" --penalty 1.0 --tfidf 'none' --name "AP PAN17 sklearn SVM rbf char 1-4grams P1.0" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "rbf" --penalty 1.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM rbf char 1-1grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "rbf" --penalty 1.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM rbf char 1-2grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "rbf" --penalty 1.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM rbf char 1-3grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "rbf" --penalty 1.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM rbf char 1-4grams P1.0 TFIDF" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "rbf" --penalty 2.0 --tfidf 'none' --name "AP PAN17 sklearn SVM rbf char 1-1grams P2.0" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "rbf" --penalty 2.0 --tfidf 'none' --name "AP PAN17 sklearn SVM rbf char 1-2grams P2.0" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "rbf" --penalty 2.0 --tfidf 'none' --name "AP PAN17 sklearn SVM rbf char 1-3grams P2.0" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "rbf" --penalty 2.0 --tfidf 'none' --name "AP PAN17 sklearn SVM rbf char 1-4grams P2.0" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "rbf" --penalty 2.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM rbf char 1-1grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "rbf" --penalty 2.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM rbf char 1-2grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "rbf" --penalty 2.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM rbf char 1-3grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "rbf" --penalty 2.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM rbf char 1-4grams P2.0 TFIDF" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "rbf" --penalty 3.0 --tfidf 'none' --name "AP PAN17 sklearn SVM rbf char 1-1grams P3.0" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "rbf" --penalty 3.0 --tfidf 'none' --name "AP PAN17 sklearn SVM rbf char 1-2grams P3.0" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "rbf" --penalty 3.0 --tfidf 'none' --name "AP PAN17 sklearn SVM rbf char 1-3grams P3.0" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "rbf" --penalty 3.0 --tfidf 'none' --name "AP PAN17 sklearn SVM rbf char 1-4grams P3.0" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 no tfidf" --output outputs/ --verbose 4

python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 1 --kernel "rbf" --penalty 3.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM rbf char 1-1grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 2 --kernel "rbf" --penalty 3.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM rbf char 1-2grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 3 --kernel "rbf" --penalty 3.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM rbf char 1-3grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
python3 sklearn_classifier_baseline.py --dataset ~/Projets/TURING/Datasets/PAN17/AuthorProfiling/json/ --feature "char" --n-grams-min 1 --n-grams-max 4 --kernel "rbf" --penalty 3.0 --tfidf 'tfidf' --name "AP PAN17 sklearn SVM rbf char 1-4grams P3.0 TFIDF" --description "Author Profiling PAN17 sklearn rbf SVM char 1-2-grams penalty 1.0 tfidf" --output outputs/ --verbose 4
